---
- name: restarting apache2 server
  hosts: localhost
  remote_user: jenkins
  become: yes
  tasks:
    - name: restarting apache2 server
      service:
        name: apache2
        state: restarted
